version: '3'
services:
  kvrocks:
    image: wactax/kvrocks:nightly
    restart: always
    container_name: kvrocks
    mem_limit: 1G
    memswap_limit: -1
    environment:
      kvrocks_port: 51002
      kvrocks_workers: 6
      kvrocks_rocksdb_compression: zstd
      kvrocks_timeout: 360
      kvrocks_rocksdb_enable_blob_files: "yes"
      kvrocks_read_options_async_io: "yes"
      kvrocks_dir: /data
      kvrocks_log_dir: /log
    volumes:
      - /tmp/benchmark/kvrocks/data:/data
      - /tmp/benchmark/kvrocks/log:/log
    ports:
      - 51002:51002
